services:
  backend:
    container_name: backend-caribe-market
    build: ./src/
    env_file:
      - ./src/.env
    ports:
      - "8080:8080"
    volumes:
      - ./src:/src
    depends_on:
      - db
    restart: always
    networks:
      - api-develop-app

  db:
    image: docker.io/bitnami/postgresql:15
    container_name: db-caribe-market
    ports:
      - 5432:5432
    env_file:
      - ./src/.env
    volumes:
      - .db:/var/postgresql
    networks:
      - api-develop-app

networks:
  api-develop-app:
    driver: bridge
